### ISSUE TITLE
Cannot build project as-is

### ISSUE THREAD

**Issue by ghost** [d-leroy/imageboard#1]
Hello, i was trying to build the project via ./mvn in the virtual machine provided on the jhipster website.

This leads to the following:

![error](https://cloud.githubusercontent.com/assets/15686975/26103549/50049fe0-3a3a-11e7-8bd3-bd4cbee2628a.JPG)

Is this intentional? Or can you give any hints on how to solve this?

**Comment by d-leroy** [comment]
Hello, it should be fixed now.
Can you confirm? I don't have this issue when I build the project.

**Comment by ghost** [comment]
Thank you, it works now.
